"""empty message

Revision ID: aadd48b3ee90
Revises: 3048a9a83446
Create Date: 2025-05-13 08:50:51.515118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aadd48b3ee90'
down_revision: Union[str, None] = '3048a9a83446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('nom')
        batch_op.drop_column('codi')
        batch_op.drop_column('preu')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preu', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('codi', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('price')
        batch_op.drop_column('name')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
